### ISSUE TITLE
Infinite login screen

### ISSUE THREAD

**Issue by KedisPL** [bc2424/UEFN-PIE#1]
![image](https://github.com/bc2424/UEFN-PIE/assets/79972336/8b2593a7-b2af-4e87-a2c8-8e7ea1bdbf5a)
![image](https://github.com/bc2424/UEFN-PIE/assets/79972336/ac68f3a4-8a21-4213-ac47-118d54ec71be)

**Comment by KedisPL** [comment]
When I delete the pak file "UEFNFortniteGame-WindowsUEFN_PIEFixes" it is possible to log in via the epic games account with exchangecode, but it crashes then.

**Comment by KedisPL** [comment]
![image](https://github.com/bc2424/UEFN-PIE/assets/79972336/616b9697-ed4e-4af4-9d47-83119b647d97)
After some modifications in files from UEFNFortniteGame-WindowsUEFN_PIEFixes.pak it works with epic account.

**Comment by bc2424** [comment]
I believe you need to load into the frontend once before the loading screen is fixed with lawin/fiddler, you can also use epic accounts with a modded pak but I like lawin more bc you don't need to keep getting the epic auth

**Comment by bc2424** [comment]
would you be able to try fiddler/lawin again and send the log if it doesn't work?

**Comment by KedisPL** [comment]
> would you be able to try fiddler/lawin again and send the log if it doesn't work?

[UnrealEditorFortnite_2.log](https://github.com/bc2424/UEFN-PIE/files/13922146/UnrealEditorFortnite_2.log)

**Comment by bc2424** [comment]
does loading into the frontend work at all? is it an infinite loading screen or does it give an error

**Comment by KedisPL** [comment]
same thing

**Comment by KedisPL** [comment]
Solution: reinstalled fiddler
